admin.cloud.microsoft
admin.exchange.microsoft.com
admin.microsoft.com
admin.powerplatform.com
admin.powerplatform.microsoft.com
admin.teams.microsoft.com
app.fabric.microsoft.com
app.powerbi.com
copilot.cloud.microsoft
engage.cloud.microsoft
entra.microsoft.com
excel.cloud.microsoft
intune.microsoft.com
loop.cloud.microsoft
m365.cloud.microsoft
onenote.cloud.microsoft
outlook.cloud.microsoft
planner.cloud.microsoft
portal.azure.com
powerpoint.cloud.microsoft
purview.microsoft.com
security.microsoft.com
teams.cloud.microsoft
word.cloud.microsoft
*.cloud.microsoft
*.static.microsoft
*.usercontent.microsoft
